<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.8.1 setup script
 * Date: Mon, 29 Apr 2013 00:18:46 +0800
 */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>